// Frontend-Project/Module2_FrontendDev/HandsOn5/student-portal-react/src/components/CourseCard.jsx
function CourseCard({ id, name, code, credits, grade, onEnroll }) {
  return (
    <article className="course-card">
      <h3>{name}</h3>
      <p>{code}</p>
      <span>{credits} Credits</span>
      <p>Grade: {grade}</p>
 
      <button onClick={() => onEnroll(id)}>Enroll</button>
    </article>
  );
}
 
export default CourseCard;

// Frontend-Project/Module2_FrontendDev/HandsOn7/student-portal-angular/src/app/course-card/course-card.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-course-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './course-card.html',
  styleUrl: './course-card.css'
})
export class CourseCard {
  @Input() name = '';
  @Input() code = '';
  @Input() credits = 0;
  @Input() grade = '';
}
